// Stripe constants
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET;

// AWS constants
const AWS_REGION = process.env.AWS_REGION;
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME;

// ComfyUI constants
const COMFYUI_URL = process.env.COMFYUI_URL;

// GOOGLE OAuth constants
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL;

// Replicate constants
const REPLICATE_UPLOAD_IMAGE_URL = process.env.REPLICATE_UPLOAD_IMAGE_URL;
const REPLICATE_UPLOAD_IMAGE_TOKEN = process.env.REPLICATE_UPLOAD_IMAGE_TOKEN;

// Color Filter API
const FAST_API_URL = process.env.FAST_API_URL;

// OpenAI constants
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

// RunPod constants
const RUNPOD_API_URL = process.env.RUNPOD_API_URL;
const RUNPOD_API_KEY = process.env.RUNPOD_API_KEY;

const BASE_URL = process.env.BASE_URL;

module.exports = {
  STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET,
  AWS_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME,
  COMFYUI_URL,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
  REPLICATE_UPLOAD_IMAGE_URL,
  REPLICATE_UPLOAD_IMAGE_TOKEN,
  FAST_API_URL,
  OPENAI_API_KEY,
  RUNPOD_API_URL,
  RUNPOD_API_KEY,
  BASE_URL
};